apiVersion: v1
kind: Service
metadata:
  name: enrollment
spec:
  selector:
    app: enrollment
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment
  template:
    metadata:
      labels:
        app: enrollment
    spec:
      containers:
        - name: enrollment
          image: enrollment # Replace with your Docker image name and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  selector:
    app: course
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: course # Replace with your Docker image name and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: payment # Replace with your Docker image name and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
